// <auto-generated at 15.1.2021. 12:07:48 />
using System;
using System.Linq;
using System.Collections.Generic;
using Norm;
using NpgsqlTypes;
using Npgsql;

namespace PgRoutiner.Test
{
    public static class PgRoutineFindUser
    {
        public const string Name = "find_user";

        /// <summary>
        /// Executes sql function "find_user"
        /// find user record
        /// </summary>
        /// <param name="id">_id bigint</param>
        /// <param name="normalizedUserName">_normalized_user_name character varying</param>
        /// <param name="normalizedEmail">_normalized_email character varying</param>
        /// <returns>IEnumerable of PgRoutiner.Test.User instances</returns>
        public static IEnumerable<User> FindUser(this NpgsqlConnection connection, long? id, string normalizedUserName, string normalizedEmail) => connection
            .AsProcedure()
            .Read<User>(Name,
                ("_id", id, NpgsqlDbType.Bigint),
                ("_normalized_user_name", normalizedUserName, NpgsqlDbType.Varchar),
                ("_normalized_email", normalizedEmail, NpgsqlDbType.Varchar));

        /// <summary>
        /// Executes sql function "find_user"
        /// find user record
        /// </summary>
        /// <param name="id">_id bigint</param>
        /// <param name="normalizedUserName">_normalized_user_name character varying</param>
        /// <param name="normalizedEmail">_normalized_email character varying</param>
        /// <param name="dummy">_dummy json</param>
        /// <returns>IEnumerable of PgRoutiner.Test.User instances</returns>
        public static IEnumerable<User> FindUser(this NpgsqlConnection connection, long? id, string normalizedUserName, string normalizedEmail, string dummy) => connection
            .AsProcedure()
            .Read<User>(Name,
                ("_id", id, NpgsqlDbType.Bigint),
                ("_normalized_user_name", normalizedUserName, NpgsqlDbType.Varchar),
                ("_normalized_email", normalizedEmail, NpgsqlDbType.Varchar),
                ("_dummy", dummy, NpgsqlDbType.Json));
    }
}
