// <auto-generated at 15.1.2021. 12:07:48 />
using System;
using System.Linq;
using System.Collections.Generic;

namespace PgRoutiner.Test
{
    public class User
    {
        public long Id { get; set; }
        public string UserName { get; set; }
        public string NormalizedUserName { get; set; }
        public string Email { get; set; }
        public string NormalizedEmail { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string ConcurrencyStamp { get; set; }
        public DateTime? LockoutEnd { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string Name { get; set; }
        public string GivenName { get; set; }
        public string PictureUrl { get; set; }
        public string Culture { get; set; }
        public string Timezone { get; set; }
        public bool UsNotation { get; set; }
        public string Data { get; set; }
        public DateTime? PrivacyAccepted { get; set; }
        public DateTime? TermsAccepted { get; set; }
        public DateTime? HealthAccepted { get; set; }
        public DateTime? ReceivesUpdates { get; set; }
        public DateTime? LastLogin { get; set; }
    }
}
