// <auto-generated />
using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using PgRoutiner.Test;
using Xunit;
using Norm;

namespace PgRoutinerTests
{
    public class DeviceLoginUnitTests : PostgreSqlUnitTestFixture
    {
        public DeviceLoginUnitTests(PostgreSqlFixture fixture) : base(fixture) { }

        [Fact]
        public void DeviceLogin_Test1()
        {
            // Arrange
            string address = default;
            string pin = default;
            string email = default;

            // Act
            var result = Connection.DeviceLogin(address, pin, email);

            // Assert
            // Assert.Equal(default(long?), result);
        }

        [Fact]
        public async Task DeviceLoginAsync_Test1()
        {
            // Arrange
            string address = default;
            string pin = default;
            string email = default;

            // Act
            var result = await Connection.DeviceLoginAsync(address, pin, email);

            // Assert
            // Assert.Equal(default(long?), result);
        }
    }
}
