// <auto-generated />
using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using PgRoutiner.Test;
using Xunit;
using Norm;

namespace PgRoutinerTests
{
    public class RemovePowerValuesUnitTests : PostgreSqlUnitTestFixture
    {
        public RemovePowerValuesUnitTests(PostgreSqlFixture fixture) : base(fixture) { }

        [Fact]
        public void RemovePowerValues_Test1()
        {
            // Arrange
            long? start = default;
            long? end = default;

            // Act
            Connection.RemovePowerValues(start, end);

            // Assert
            // Assert.Equal(default(string), Connection.Read<string>("select your assertion value").Single());
        }

        [Fact]
        public async Task RemovePowerValuesAsync_Test1()
        {
            // Arrange
            long? start = default;
            long? end = default;

            // Act
            await Connection.RemovePowerValuesAsync(start, end);

            // Assert
            // Assert.Equal(default(string), Connection.Read<string>("select your assertion value").Single());
        }
    }
}
