// <auto-generated />
using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using PgRoutiner.Test;
using Xunit;
using Norm;

namespace PgRoutinerTests
{
    public class UpsertPowerValuesUnitTests : PostgreSqlUnitTestFixture
    {
        public UpsertPowerValuesUnitTests(PostgreSqlFixture fixture) : base(fixture) { }

        [Fact]
        public void UpsertPowerValues_Test1()
        {
            // Arrange
            string address = default;
            string data = default;

            // Act
            var result = Connection.UpsertPowerValues(address, data);

            // Assert
            // Assert.Equal(default(long?), result);
        }

        [Fact]
        public async Task UpsertPowerValuesAsync_Test1()
        {
            // Arrange
            string address = default;
            string data = default;

            // Act
            var result = await Connection.UpsertPowerValuesAsync(address, data);

            // Assert
            // Assert.Equal(default(long?), result);
        }
    }
}
