// <auto-generated />
using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using PgRoutiner.Test;
using Xunit;
using Norm;

namespace PgRoutinerTests
{
    public class UpsertEnergyValuesUnitTests : PostgreSqlUnitTestFixture
    {
        public UpsertEnergyValuesUnitTests(PostgreSqlFixture fixture) : base(fixture) { }

        [Fact]
        public void UpsertEnergyValues_Test1()
        {
            // Arrange
            string address = default;
            string data = default;

            // Act
            var result = Connection.UpsertEnergyValues(address, data);

            // Assert
            // Assert.Equal(default(long?), result);
        }

        [Fact]
        public async Task UpsertEnergyValuesAsync_Test1()
        {
            // Arrange
            string address = default;
            string data = default;

            // Act
            var result = await Connection.UpsertEnergyValuesAsync(address, data);

            // Assert
            // Assert.Equal(default(long?), result);
        }
    }
}
