// <auto-generated />
using System;
using System.Linq;
using System.Collections.Generic;

namespace PgRoutiner.Models
{
    public class GetUserResult
    {
        public long? Id { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string Data { get; set; }
        public string[] Providers { get; set; }
        public int? RegionId { get; set; }
        public string Country { get; set; }
        public string Timezone { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Accessed { get; set; }
        public DateTime? Accepted { get; set; }
    }
}
