// <auto-generated />
using System;
using System.Linq;
using System.Collections.Generic;

namespace PgRoutiner.Models
{
    public class UpdateUserAccessResult
    {
        public DateTime? Accepted { get; set; }
        public string Timezone { get; set; }
    }
}
