// <auto-generated />
using System;
using System.Linq;
using System.Collections.Generic;

namespace PgRoutiner.Models
{
    public class UpsertUserResult
    {
        public int? Id { get; set; }
        public bool? IsNew { get; set; }
    }
}
