using System.Collections.Generic;

namespace PgRoutiner
{
    public partial class RoutineCode : Code
    {
        private static readonly Dictionary<string, (string Name, bool IsRange)> ParamTypeMapping = new()
        {
            {"refcursor", ("Refcursor", false)},
            {"tsvector", ("TsVector", false)},
            {"cidr", ("Cidr", false)},
            {"timestamptz", ("TimestampTz", false)},
            {"name", ("Name", false)},
            {"inet", ("Inet", false)},
            {"lseg", ("Lseg", false)},
            {"int8", ("Bigint", false)},
            {"_char", ("Char", false)},
            {"unknown", ("Unknown", false)},
            {"tsquery", ("TsQuery", false)},
            {"float4", ("Real", false)},
            {"timestamp", ("Timestamp", false)},
            {"gtsvector", ("TsVector", false)},
            {"circle", ("Circle", false)},
            {"numeric", ("Numeric", false)},
            {"pg_type", ("Regtype", false)},
            {"regconfig", ("Regconfig", false)},
            {"timetz", ("TimeTZ", false)},
            {"daterange", ("Date", true)},
            {"box", ("Box", false)},
            {"_float4", ("Real", false)},
            {"int4range", ("Integer", true)},
            {"cid", ("Cid", false)},
            {"_regtype", ("Regtype", false)},
            {"_varchar", ("Varchar", false)},
            {"_text", ("Text", false)},
            {"date", ("Date", false)},
            {"xid", ("Xid", false)},
            {"bool", ("Boolean", false)},
            {"_oid", ("Oid", false)},
            {"polygon", ("Polygon", false)},
            {"time", ("Time", false)},
            {"int2vector", ("Int2Vector", false)},
            {"_int4", ("Integer", false)},
            {"int4", ("Integer", false)},
            {"_interval", ("Interval", false)},
            {"_int8", ("Bigint", false)},
            {"int8range", ("Bigint", true)},
            {"interval", ("Interval", false)},
            {"xml", ("Xml", false)},
            {"char", ("Char", false)},
            {"macaddr8", ("MacAddr8", false)},
            {"varchar", ("Varchar", false)},
            {"float8", ("Double", false)},
            {"json", ("Json", false)},
            {"_name", ("Name", false)},
            {"money", ("Money", false)},
            {"text", ("Text", false)},
            {"_float8", ("Double", false)},
            {"regtype", ("Regtype", false)},
            {"bit", ("Bit", false)},
            {"tid", ("Tid", false)},
            {"line", ("Line", false)},
            {"oidvector", ("Oidvector", false)},
            {"int2", ("Smallint", false)},
            {"uuid", ("Uuid", false)},
            {"path", ("Path", false)},
            {"jsonb", ("Jsonb", false)},
            {"bytea", ("Bytea", false)},
            {"_bool", ("Boolean", false)},
            {"macaddr", ("MacAddr", false)},
            {"point", ("Point", false)},
            {"varbit", ("Varbit", false)},
            {"oid", ("Oid", false)},
            {"_int2", ("Smallint", false)}
        };
    }
}
